# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Translate README

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'README.md'  # Only trigger on README.md changes
    paths-ignore:
      - 'docs/**'    # Ignore changes in docs directory

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      # Add commit message that ReadTheDocs can ignore
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          
      # ISO Language Codes: https://cloud.google.com/translate/docs/languages  
      - name: Adding README - Chinese Simplified
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh-CN
          COMMIT_MESSAGE: '[skip docs] Update README translations'  # ReadTheDocs will ignore this
      - name: Adding README - Chinese Traditional
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh-TW
      - name: Adding README - Hindi
        uses: dephraiim/translate-readme@main
        with:
          LANG: hi
      - name: Adding README - Arabic
        uses: dephraiim/translate-readme@main
        with:
          LANG: ar
      - name: Adding README - French
        uses: dephraiim/translate-readme@main
        with:
          LANG: fr
      - name: Adding README - German
        uses: dephraiim/translate-readme@main
        with:
          LANG: de
      - name: Adding README - Dutch
        uses: dephraiim/translate-readme@main
        with:
          LANG: nl
      - name: Adding README - Spanish
        uses: dephraiim/translate-readme@main
        with:
          LANG: es
